#
# Copyright 2017-present Li Ying.
# Licensed under the MIT License.
#

POM_ARTIFACT_ID=crypto-util
VERSION_NAME=1.0.0
POM_NAME=Crypto Util
POM_DESCRIPTION=A lightweight crypto library for Android and Java that offers out-of-the-box functionality
POM_INCEPTION_YEAR=2017
POM_URL=https://github.com/liying2008/DigestUtil
