# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
mavenCentralPublishing=true
signAllPublications=true
GROUP=cc.duduhuo.util

POM_LICENSE_NAME=MIT License
POM_LICENSE_URL=https://opensource.org/license/MIT
POM_LICENSE_DIST=repo

POM_SCM_URL=https://github.com/liying2008/DigestUtil
POM_SCM_CONNECTION=scm:git:github.com/liying2008/DigestUtil.git
POM_SCM_DEV_CONNECTION=scm:git:ssh://github.com/liying2008/DigestUtil.git

POM_DEVELOPER_ID=liying2008
POM_DEVELOPER_NAME=Li Ying
POM_DEVELOPER_EMAIL=liruoer2008@yeah.net
POM_DEVELOPER_URL=https://github.com/liying2008
