#
# Copyright 2017-present Li Ying.
# Licensed under the MIT License.
#

POM_ARTIFACT_ID=digest-util-ktx
VERSION_NAME=2.1.0
POM_NAME=Digest Util Kotlin Extensions
POM_DESCRIPTION=A lightweight digest and base64 library for Android and Java that offers out-of-the-box functionality
POM_INCEPTION_YEAR=2017
POM_URL=https://github.com/liying2008/DigestUtil
